#!/bin/sh
bash $HOME/Dotfiles/startup.sh &
pkill sxhkd
sxhkd -c $HOME/Dotfiles/sxhkd/sxhkdrc #-c $HOME/Dotfiles/bspwm/sxhkdrc &

bspc config border_width         2
bspc config window_gap          15
bspc config split_ratio          0.52
bspc config borderless_monocle   true
# bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc monitor -d 1 2 3 4 5 6 7 9 10
