matches:
  - triggers: [":Alpha"]
    replace: "Î‘"

  - triggers: [":alpha"]
    replace: "Î±"

  - triggers: [":Beta"]
    replace: "Î’"

  - triggers: [":beta"]
    replace: "Î²"

  - triggers: [":varbeta"]
    replace: "Ï"

  - triggers: [":Delta"]
    replace: "Î”"

  - triggers: [":delta"]
    replace: "Î´"

  - triggers: [":Epsilon"]
    replace: "Î•"

  - triggers: [":epsilon"]
    replace: "Ïµ"

  - triggers: [":varepsilon"]
    replace: "Îµ"

  - triggers: [":Phi"]
    replace: "Î¦"

  - triggers: [":phi"]
    replace: "ğœ™"

  - triggers: [":varphi"]
    replace: "Ï†"

  - triggers: [":Gamma"]
    replace: "Î“"

  - triggers: [":gamma"]
    replace: "Î³"

  - triggers: [":Eta"]
    replace: "Î—"

  - triggers: [":eta"]
    replace: "Î·"

  - triggers: [":Iota"]
    replace: "Î™"

  - triggers: [":iota"]
    replace: "Î¹"

  - triggers: [":Theta"]
    replace: "Î˜"

  - triggers: [":theta"]
    replace: "Î¸"

  - triggers: [":vartheta"]
    replace: "Ï‘"

  - triggers: [":Kappa"]
    replace: "Îš"

  - triggers: [":kappa"]
    replace: "Îº"

  - triggers: [":varkappa"]
    replace: "Ï°"

  - triggers: [":Lambda"]
    replace: "Î›"

  - triggers: [":lambda"]
    replace: "Î»"

  - triggers: [":Mu"]
    replace: "Îœ"

  - triggers: [":mu"]
    replace: "Î¼"

  - triggers: [":Nu"]
    replace: "Î"

  - triggers: [":nu"]
    replace: "Î½"

  - trigger: ":Omicron"
    replace: "ÎŸ"

  - trigger: ":omicron"
    replace: "Î¿"

  - trigger: ":Pi"
    replace: "Î "

  - trigger: ":pi"
    replace: "Ï€"

  - triggers: [":varpi"]
    replace: "Ï–"

  - triggers: [":Chi"]
    replace: "Î§"

  - triggers: [":chi"]
    replace: "Ï‡"

  - triggers: [":Rho"]
    replace: "Î¡"

  - triggers: [":rho"]
    replace: "Ï"

  - triggers: [":varrho"]
    replace: "Ï±"

  - triggers: [":Sigma"]
    replace: "Î£"

  - triggers: [":sigma"]
    replace: "Ïƒ"

  - triggers: [":varsigma"]
    replace: "Ï‚"

  - trigger: ":Tau"
    replace: "Î¤"

  - trigger: ":tau"
    replace: "Ï„"

  - triggers: [":Upsilon"]
    replace: "Î¥"

  - triggers: [":upsilon"]
    replace: "Ï…"

  - triggers: [":Omega"]
    replace: "Î©"

  - triggers: [":omega"]
    replace: "Ï‰"

  - trigger: ":Xi"
    replace: "Î"

  - trigger: ":xi"
    replace: "Î¾"

  - trigger: ":Psi"
    replace: "Î¨"

  - trigger: ":psi"
    replace: "Ïˆ"

  - triggers: [":varPsi"]
    replace: "â²®"

  - triggers: [":varpsi"]
    replace: "â²¯"

  - triggers: [":Zeta"]
    replace: "Î–"

  - triggers: [":zeta"]
    replace: "Î¶"
