#!/bin/bash

# meant to work only with stock arch linux
# inspired by pfetch

# not completed yet

# TODO:
# logo
# colors
# alignment

main() {
    ascii
    title
    # echo "os" os
    # echo "kernel" kernel
    # echo "uptime" uptime
    # echo "pkgs" pkgs
    # echo "memory" memory
    os
    host
    kernel
    uptime
    pkgs
    memory
}

ascii() {
# ${c6}       /\\
# ${c6}      /  \\
# ${c6}     /\\   \\
# ${c4}    /      \\
# ${c4}   /   ,,   \\
# ${c4}  /   |  |  -\\
# ${c4} /_-''    ''-_\\
:
}

os() {
    echo "os Arch Linux"
}

host() {
    echo "host $(uname -n)"
}

title() {
    echo "$(whoami)@$(uname -n)"
}

kernel() {
    echo "kernel $(uname -r)"
}

uptime() {
    echo "uptime $(uptime --pretty | sed 's/up //' | sed 's/\ years\?,/y/' | sed 's/\ weeks\?,/w/' | sed 's/\ days\?,/d/' | sed 's/\ hours\?,\?/h/' | sed 's/\ minutes\?/m/')"
}

pkgs() {
    echo "pkgs $(pacman -Qq | wc -l)"
}

memory() {
    echo "memory $(free -m | sed -n 's/^Mem:\s\+[0-9]\+\s\+\([0-9]\+\)\s.\+/\1/p')"
}

main
