#!/bin/bash

set -e

# clean unneded dependencies
yay -Yc

# clean yay's cache
yay -Sc

# remove orphan packages
sudo pacman -Rns $(pacman -Qtdq)

# clean pacman's cache
paccache -r

# empty the trash
# trash-empty
