#!/bin/bash

script="$(ls $HOME/Scripts | rofi -dmenu -i -p "Scripts")"
# exec st -e "$script"
if [ "$script" == "" ]; then
    :
else
    # exec st -e sh -c "exec $script; exec /bin/zsh; read"
    # xargs -i --no-run-if-empty /bin/bash -c "{}" "$script"
    exec $script
fi
