#!/bin/bash

wm="$(echo "i3|Bspwm|Qtile|Xmonad|AwesomeWM|Dwm|LeftWM|Openbox" | rofi -dmenu -p "Exit WM" -sep "|")"
if [ "$wm" == "" ]; then
    :
else
    confirmation="$(echo "Yes|No" | rofi -dmenu -i -p "Are you sure?" -sep "|")"
fi

exit_wm () {
    case $1 in
        i3)
            exec i3-msg exit
            ;;
        bspwm)
            exec bspc quit
            ;;
        qtile)
            exec pkill qtile
            ;;
        xmonad)
            exec pkill xmonad
            ;;
        awesomeWM)
            exec pkill awesome
            ;;
        dwm)
            exec pkill dwm
            exec killall dwm
            ;;
        spectrwm)
            exec pkill spectrwm
            ;;
        leftWM)
            exec pkill leftwm
            ;;
        openbox)
            exec openbox --exit
            ;;
    esac
}

if [ "$confirmation" == "Yes" ]; then
    exit_wm "$wm"
elif [ "$confirmation" == "No" ]; then
    :
elif [ "$confirmation" == "" ]; then
    :
fi
