#!/bin/bash

process="$(ps cux | awk '{print $11}' | tail -n +2 | rofi -dmenu -i -p "Kill Process")"

if [ "$process" == "" ]; then
    :
else
    confirmation="$(echo "Yes|No" | rofi -dmenu -p "Do you really want to kill $process?" -sep "|")"
    if [ "$confirmation" == "Yes" ]; then
        pkill "$process"
    elif [ "$confirmation" == "No" ]; then
        :
    fi
fi
