#!/bin/bash

## incomplete script
## this does not work yet

if [ $# -eq 0 ]; then
    nvim ~/Desktop/reminders.md
else
    item=$*
    item="- [REMINDER] $item"
    echo "$item" >> ~/Desktop/reminders.md
    echo "Reminder Added!"
fi
