#!/bin/bash

default_wm="startplasma-wayland"

# $1:name, $2:path
function start() {
    echo "Starting $1"
    exec startx /usr/bin/"$2" 2>/dev/null
}

wm="$(echo 'KDE Plasma
i3
Hyprland
Bspwm
Qtile
Xmonad
AwesomeWM
Dwm
Spectrwm
Openbox
Xfce
None' | fzf --reverse --border=rounded --cycle --height=50% --padding=1 | tr '[:upper:]' '[:lower:]')"

if [ "$wm" = "" ]; then
    # echo "Starting $default_wm"
    # exec startx "$default_wm"
    exec "startplasma-wayland"
else
    case $wm in
        "kde plasma")
            # export DESKTOP_SESSION=plasma
            # start "KDE Plasma" "startplasma-x11"
            exec "startplasma-wayland"
            ;;
        "i3")
            start "i3" "i3"
            ;;
        "hyprland")
            exec "Hyprland"
            ;;
        "bspwm")
            start "Bspwm" "bspwm"
            ;;
        "qtile")
            echo "Starting Qtile"
            exec startx /usr/bin/qtile start
            ;;
        "xmonad")
            start "Xmonad" "xmonad"
            ;;
        "awesomewm")
            start "AwesomeWM" "awesome"
            ;;
        "dwm")
            echo "Starting Dwm"
            exec startx /usr/local/bin/dwm 2>/dev/null
            ;;
        "spectrwm")
            start "Spectrwm" "spectrwm"
            ;;
        "openbox")
            start "Openbox" "openbox-session"
            ;;
        "xfce")
            start "Xfce" "startxfce4"
            ;;
        "none")
            exit 0
            ;;
        *)
            echo "Invalid input"
            exit 1
    esac

fi
