#!/bin/python3
# vim: filetype=python

from os import system
import sys

def exit():
    sys.exit()

print("""WM/DE:
- i3 (1)
- Bspwm (2)
- Qtile (3)
- Xmonad (4)
- AwesomeWM (5)
- Openbox (6)
- KDE Plasma (7)
- Dont't start xorg (0)
""")

wm = str(input("> ").strip().rstrip())

if wm == "1":
    system("startx /usr/bin/i3")
elif wm == "2":
    system("startx /usr/bin/bspwm")
elif wm == "3":
    system("startx /usr/bin/qtile start")
elif wm == "4":
    system("startx /usr/bin/xmonad")
elif wm == "5":
    system("startx /usr/bin/awesome")
elif wm == "6":
    system("startx /usr/bin/openbox-session")
elif wm == "7":
    system("export DESKTOP_SESSION=plasma && startx /usr/bin/startplasma-x11")
elif wm == "0":
    pass
else:
    print("Invalid input")
    exit()

